
table_stars = (
    'O',
    'B',
    'A',
    'F',
    'G',
    'K',
    'M',
    'A_BlueWhiteSuperGiant',
    'F_WhiteSuperGiant',
    'M_RedSuperGiant',
    'K_OrangeGiant',
    'M_RedGiant',
    'L',
    'T',
    'Y',
    'TTS',
    'AeBe',
    'MS',
    'S',
    'CN',
    'CJ',
    # 'C',
    'H',
    'N',
    # 'D',
    'DA',
    'DAB',
    'DAV',
    'DAZ',
    'DB',
    'DBV',
    'DBZ',
    'DC',
    'DCV',
    # 'DQ',
    # 'W',
    'WC',
    'WO',
    'WN',
    'WNC',
    'Sudarsky class V gas giant',
    'Sudarsky class IV gas giant',
    'Sudarsky class III gas giant',
    'Sudarsky class II gas giant',
    'Sudarsky class I gas giant',
    'Gas giant with water based life',
    'Gas giant with ammonia based life',
    'Helium rich gas giant',
    'Water giant',
    # 'Helium gas giant',
    'Earthlike body',
    'Ammonia world',
    'Water world',
    'Water world (Terraformable)',
    'Metal rich body',
    'Metal rich body (Terraformable)',
    'Metal rich body (Landable)',
    'High metal content body',
    'High metal content body (Terraformable)',
    'High metal content body (Landable)',
    'Rocky body',
    'Rocky body (Terraformable)',
    'Rocky body (Landable)',
    'Rocky ice body',
    'Rocky ice body (Landable)',
    'Icy body',
    'Icy body (Landable)',
)

object_formulas = [
    {"FormulaType":'Count',"default":r'COUNTIFS(objects!$Object,$A{0:d})',"landable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Landable,TRUE)',"terraformable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$TerraformState,"Terraformable")'},
    {"FormulaType":'Rings',"default":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Ring,"x")',"landable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Ring,"x",objects!$Landable,TRUE)',"terraformable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Ring,"x",objects!$TerraformState,"Terraformable")'},
    {"FormulaType":'Mass(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Mass))))'},
    {"FormulaType":'Mass(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Mass))))'},
    {"FormulaType":'Radius(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Radius)))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Radius))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Radius))))'},
    {"FormulaType":'Radius(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Radius)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Radius))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Radius))))'},
    {"FormulaType":'Density(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Density)))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Density))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Density))))'},
    {"FormulaType":'Density(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Density)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Density))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Density))))'},
    {"FormulaType":'Temp(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",if(objects!$SurfaceTemperature<>"",objects!$SurfaceTemperature))))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$SurfaceTemperature<>"",objects!$SurfaceTemperature))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$SurfaceTemperature<>"",IF(objects!$TerraformState = "Terraformable",objects!$SurfaceTemperature)))))'},
    {"FormulaType":'Temp(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$SurfaceTemperature)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$SurfaceTemperature))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$SurfaceTemperature))))'},
    {"FormulaType":'Velocity(km/s)(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$OrbitalVelocity)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$OrbitalVelocity))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$OrbitalVelocity))))'},
    {"FormulaType":'OrbitPeriod(seconds)(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$OrbitalPeriod<>"",objects!$OrbitalPeriod))))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$OrbitalPeriod))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$OrbitalPeriod))))'},
    {"FormulaType":'OrbitPeriod(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$OrbitalPeriod)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$OrbitalPeriod))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$OrbitalPeriod))))'}
    # {"formulaType":'',"default":'',"landable":'',"terraformable":''},
    # {"FormulaType":'',"default":'',"landable":'',"terraformable":''},
    # {"FormulaType":'',"default":'',"landable":'',"terraformable":''},
    # {"FormulaType":'',"default":'',"landable":'',"terraformable":''},
    # ["1"]

    # Need a structure that encompasses all formulas that can be used for any added objects.
]

object_formulas2 = [
    {"FormulaType":'Count',"default":r'COUNTIFS(objects!$Object,$A{0:d})',"landable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Landable,TRUE)',"terraformable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$TerraformState,"Terraformable")'},
    {"FormulaType":'Rings',"default":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Ring,"x")',"landable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Ring,"x",objects!$Landable,TRUE)',"terraformable":r'COUNTIFS(objects!$Object,$A{0:d},objects!$Ring,"x",objects!$TerraformState,"Terraformable")'},
    {"FormulaType":'Mass(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Mass))))'},
    {"FormulaType":'Mass(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Mass)))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Mass))))'},
    {"FormulaType":'Radius(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Radius)))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Radius))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Radius))))'},
    {"FormulaType":'Radius(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Radius)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Radius))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Radius))))'},
    {"FormulaType":'Density(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Density)))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Density))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Density))))'},
    {"FormulaType":'Density(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$Density)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$Density))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$Density))))'},
    {"FormulaType":'Temp(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$SurfaceTemperature)))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$SurfaceTemperature<>"",objects!$SurfaceTemperature))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$SurfaceTemperature))))'},
    {"FormulaType":'Temp(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$SurfaceTemperature)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$SurfaceTemperature))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$SurfaceTemperature))))'},
    {"FormulaType":'Velocity(km/s)(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$OrbitalVelocity)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$OrbitalVelocity))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$OrbitalVelocity))))'},
    {"FormulaType":'OrbitPeriod(seconds)(MIN)',"default":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$OrbitalPeriod<>"",objects!$OrbitalPeriod))))',"landable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$OrbitalPeriod))))',"terraformable":'=MIN(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$OrbitalPeriod))))'},
    {"FormulaType":'OrbitPeriod(MAX)',"default":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",objects!$OrbitalPeriod)))',"landable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$Landable = TRUE,objects!$OrbitalPeriod))))',"terraformable":'=MAX(IF(objects!$Object=$A{0:d},IF(objects!$BoxelName<>"",IF(objects!$TerraformState = "Terraformable",objects!$OrbitalPeriod))))'}
    # {"formulaType":'',"default":'',"landable":'',"terraformable":''},
    # {"FormulaType":'',"default":'',"landable":'',"terraformable":''},
    # {"FormulaType":'',"default":'',"landable":'',"terraformable":''},
    # {"FormulaType":'',"default":'',"landable":'',"terraformable":''},
    # ["1"]

    # Need a structure that encompasses all formulas that can be used for any added objects.
]


# DELETEME 9, 20, 8
helper_formulas = {
    "Gravitational Constant":6.67408E-11,
    "Astronomical Unit":499.004,
    "Seconds in one standard year":31558150,
    "Days in one standard year":365.2563657
}