
table_stars = (
    'O',
    'B',
    'A',
    'F',
    'G',
    'K',
    'M',
    'A_BlueWhiteSuperGiant',
    'F_WhiteSuperGiant',
    'K_OrangeGiant',
    'M_RedSuperGiant',
    'M_RedGiant',
    'L',
    'Y',
    'T',
    'TTS',
    'AeBe',
    'MS',
    'S',
    'CN',
    'CJ',
    'C',
    'H',
    'N',
    'D',
    'DA',
    'DAB',
    'DAV',
    'DAZ',
    'DB',
    'DBV',
    'DBZ',
    'DC',
    'DCV',
    'DQ',
    'W',
    'WC',
    'WN',
    'WNC',
    'WO',
    'Sudarsky class I gas giant',
    'Sudarsky class II gas giant',
    'Sudarsky class III gas giant',
    'Sudarsky class IV gas giant',
    'Sudarsky class V gas giant',
    'Gas giant with ammonia based life',
    'Gas giant with water based life',
    'Helium rich gas giant',
    'Helium gas giant',
    'Icy body',
    'Rocky ice body',
    'Rocky body',
    'High metal content body',
    'Metal rich body',
    'Water world',
    'Ammonia world',
    'Earthlike body',
    'Water giant'
)

helper_formulas = {
    "Gravitational Constant":6.67408E-11,
    "Astronomical Unit":499.004,
    "Seconds in one standard year":31558150,
    "Days in one standard year":365.2563657
}